/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package grafica;

import com.toedter.calendar.JDateChooser;
import datos.Cita;
import datos.OpcionCita;
import java.util.Calendar;
import java.util.Date;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import logica.GestorCitas;

/**
 *
 * @author TP303
 */
public class Ventana extends javax.swing.JFrame {
    private OpcionCita laopcion;
    private JDateChooser cjFechaNac;
    private JDateChooser cjFechaCita;
    
    private DefaultTableModel modelTabla;

    /**
     * Creates new form Ventana
     */
    public Ventana() {
        initComponents();
        cjFechaNac = new JDateChooser();
        getContentPane().add(cjFechaNac);
        cjFechaNac.setBounds(420, 30, 150, 20);
        cjFechaCita = new JDateChooser();
        getContentPane().add(cjFechaCita);
        cjFechaCita.setBounds(40, 110, 150, 20);
        
        this.cargarCitas();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoOpciones = new javax.swing.ButtonGroup();
        cjNombre = new javax.swing.JTextField();
        cjIdentificacion = new javax.swing.JTextField();
        opMedicina = new javax.swing.JRadioButton();
        opOdontologia = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btGuardar = new javax.swing.JButton();
        btSalir = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaCitas = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);
        getContentPane().add(cjNombre);
        cjNombre.setBounds(50, 30, 160, 22);
        getContentPane().add(cjIdentificacion);
        cjIdentificacion.setBounds(230, 30, 160, 22);

        grupoOpciones.add(opMedicina);
        opMedicina.setText("MEDICINE");
        opMedicina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opMedicinaActionPerformed(evt);
            }
        });
        getContentPane().add(opMedicina);
        opMedicina.setBounds(200, 100, 120, 25);

        grupoOpciones.add(opOdontologia);
        opOdontologia.setText("ODONTOLOGY");
        opOdontologia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opOdontologiaActionPerformed(evt);
            }
        });
        getContentPane().add(opOdontologia);
        opOdontologia.setBounds(200, 120, 140, 25);

        jLabel1.setText("NAME");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(48, 10, 90, 16);

        jLabel2.setText("IDENTIFICATION");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(240, 10, 130, 16);

        jLabel3.setText("BIRTHDATE");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(430, 10, 120, 16);

        jLabel4.setText("DATE");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(50, 90, 90, 16);

        btGuardar.setText("SAVE");
        btGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btGuardarActionPerformed(evt);
            }
        });
        getContentPane().add(btGuardar);
        btGuardar.setBounds(320, 170, 130, 25);

        btSalir.setText("EXIT");
        btSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalirActionPerformed(evt);
            }
        });
        getContentPane().add(btSalir);
        btSalir.setBounds(460, 170, 110, 25);

        tablaCitas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablaCitas);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(30, 220, 540, 280);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 204));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Construído por : Vinni 2022");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(360, 510, 230, 14);

        setSize(new java.awt.Dimension(614, 565));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void opMedicinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opMedicinaActionPerformed
        // TODO add your handling code here:
        this.clickOpcion(1);
    }//GEN-LAST:event_opMedicinaActionPerformed

    private void opOdontologiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opOdontologiaActionPerformed
        // TODO add your handling code here:
        this.clickOpcion(2);
    }//GEN-LAST:event_opOdontologiaActionPerformed

    private void btGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btGuardarActionPerformed
        // TODO add your handling code here:
        this.crearCita();
    }//GEN-LAST:event_btGuardarActionPerformed

    private void btSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana().setVisible(true);
            }
        });
    }// FIN DE MAIN
    private void clickOpcion(int opcion){
        //JOptionPane.showMessageDialog(this, opcion);
        if (opcion == 1){
            this.laopcion = OpcionCita.MEDICINA_GENERAL;
        }else{
            this.laopcion = OpcionCita.ODONTOLOGIA;
        }
    }
    private void crearCita(){
        
        String nombre = cjNombre.getText();
        String identificacion = cjIdentificacion.getText();
        Date fechaNac = cjFechaNac.getDate();//this.convertirStrinToDate(cjFechaNac.getText());
        Date fecha = cjFechaCita.getDate();//this.convertirStrinToDate(cjFechaCita.getText());
        
        GestorCitas g = new GestorCitas();
        Cita c = g.crearCita(nombre, identificacion, fechaNac, fecha, this.laopcion);
        if (c != null){
            this.cargarCitas();
            JOptionPane.showMessageDialog(this, "Creo la cita ->"+c);
            
        }else{
            JOptionPane.showMessageDialog(this, "Noooo Creo la cita");
        }
        
    }
    private Date convertirStrinToDate(String fecha){
        //"22/33/2222"
        if (fecha == null || fecha.isEmpty()){
            return new Date();
        }else{
            String lafecha[] = fecha.split("/");
            Calendar c = Calendar.getInstance();
            c.set(Integer.parseInt(lafecha[2]), 
                Integer.parseInt(lafecha[1]), 
                Integer.parseInt(lafecha[0]));
        return c.getTime();
        }
        
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btGuardar;
    private javax.swing.JButton btSalir;
    private javax.swing.JTextField cjIdentificacion;
    private javax.swing.JTextField cjNombre;
    private javax.swing.ButtonGroup grupoOpciones;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton opMedicina;
    private javax.swing.JRadioButton opOdontologia;
    private javax.swing.JTable tablaCitas;
    // End of variables declaration//GEN-END:variables

    private void cargarCitas() {
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("CODE");
        modelo.addColumn("DATE");
        modelo.addColumn("PATIENT IDENTIFICATION");
        modelo.addColumn("PATIENT NAME");
        modelo.addColumn("TYPE");
        
        GestorCitas gestor = new GestorCitas();
        Map<String, Cita> lista = gestor.obtenerLista();
        for (Map.Entry<String, Cita> dato  : lista.entrySet()) {
            Cita lacita = dato.getValue();
            Object[] datos = {
                lacita.getCodigo(),
                utilidades.Util.convertirDateString(lacita.obtenerFecha()),
                lacita.obtenerPaciente().obtenerIdentificacion(),
                lacita.obtenerPaciente().obtenerNombre(),
                lacita.obtenerOpcion().toString()
            };
            modelo.addRow(datos);
            
        }
        this.tablaCitas.setModel(modelo);
    }
    
}//FIN DE CLASE
