/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package grafica;

import datos.Cita;
import datos.OpcionCita;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JOptionPane;
import logica.GestorCitas;

/**
 *
 * @author TP303
 */
public class Ventana extends javax.swing.JFrame {

    /**
     * Creates new form Ventana
     */
    public Ventana() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cjNombre = new javax.swing.JTextField();
        cjIdentificacion = new javax.swing.JTextField();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        cjFechaNac = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cjFechaCita = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        btGuardar = new javax.swing.JButton();
        btSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);
        getContentPane().add(cjNombre);
        cjNombre.setBounds(50, 30, 160, 20);
        getContentPane().add(cjIdentificacion);
        cjIdentificacion.setBounds(230, 30, 160, 20);

        jRadioButton1.setText("MEDICINE");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton1);
        jRadioButton1.setBounds(200, 100, 120, 23);

        jRadioButton2.setText("ODONTOLOGY");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton2);
        jRadioButton2.setBounds(200, 120, 140, 23);
        getContentPane().add(cjFechaNac);
        cjFechaNac.setBounds(420, 30, 150, 20);

        jLabel1.setText("NAME");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(110, 10, 28, 14);

        jLabel2.setText("IDENTIFICATION");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(240, 10, 110, 14);

        jLabel3.setText("BIRTHDATE");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(450, 10, 100, 14);
        getContentPane().add(cjFechaCita);
        cjFechaCita.setBounds(40, 110, 150, 20);

        jLabel4.setText("DATE");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(70, 90, 70, 14);

        btGuardar.setText("SAVE");
        btGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btGuardarActionPerformed(evt);
            }
        });
        getContentPane().add(btGuardar);
        btGuardar.setBounds(320, 170, 130, 23);

        btSalir.setText("EXIT");
        getContentPane().add(btSalir);
        btSalir.setBounds(460, 170, 110, 23);

        setSize(new java.awt.Dimension(609, 247));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void btGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btGuardarActionPerformed
        // TODO add your handling code here:
        this.crearCita();
    }//GEN-LAST:event_btGuardarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana().setVisible(true);
            }
        });
    }// FIN DE MAIN
    
    private void crearCita(){
        
        String nombre = cjNombre.getText();
        String identificacion = cjIdentificacion.getText();
        Date fechaNac = this.convertirStrinToDate(cjFechaNac.getText());
        Date fecha = this.convertirStrinToDate(cjFechaCita.getText());
        
        GestorCitas g = new GestorCitas();
        Cita c = g.crearCita(nombre, identificacion, fechaNac, fecha, OpcionCita.PEDIATRIA);
        if (c != null){
            JOptionPane.showMessageDialog(this, "Creo la cita");
        }else{
            JOptionPane.showMessageDialog(this, "Noooo Creo la cita");
        }
        
    }
    private Date convertirStrinToDate(String fecha){
        //"22/33/2222"
        if (fecha == null || fecha.isEmpty()){
            return new Date();
        }else{
            String lafecha[] = fecha.split("/");
            Calendar c = Calendar.getInstance();
            c.set(Integer.parseInt(lafecha[2]), 
                Integer.parseInt(lafecha[1]), 
                Integer.parseInt(lafecha[0]));
        return c.getTime();
        }
        
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btGuardar;
    private javax.swing.JButton btSalir;
    private javax.swing.JTextField cjFechaCita;
    private javax.swing.JTextField cjFechaNac;
    private javax.swing.JTextField cjIdentificacion;
    private javax.swing.JTextField cjNombre;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    // End of variables declaration//GEN-END:variables
}//FIN DE CLASE
